apiVersion: v1
kind: ConfigMap
metadata:
  name: drug-interaction
  namespace: helixcare
  labels: { app.kubernetes.io/name: drug-interaction, helixcare.io/domain: pharmacy }
data:
  LOG_LEVEL: info
  PORT: "50122"
