apiVersion: v1
kind: ConfigMap
metadata:
  name: equipment-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: equipment-service, helixcare.io/domain: inventory }
data:
  LOG_LEVEL: info
  PORT: "50261"
