apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: rbac-service, helixcare.io/domain: identity }
data:
  LOG_LEVEL: info
  PORT: "50022"
