apiVersion: v1
kind: Service
metadata:
  name: rbac-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: rbac-service, helixcare.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50022, targetPort: 50022 }]
  selector: { app.kubernetes.io/name: rbac-service }
