apiVersion: v1
kind: Service
metadata:
  name: lab-order-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: lab-order-service, helixcare.io/domain: diagnostics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50100, targetPort: 50100 }]
  selector: { app.kubernetes.io/name: lab-order-service }
