apiVersion: v1
kind: Service
metadata:
  name: sso-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: sso-service, helixcare.io/domain: identity }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50021, targetPort: 50021 }]
  selector: { app.kubernetes.io/name: sso-service }
