apiVersion: v1
kind: Service
metadata:
  name: {{ include "medical-supply-service.fullname" . }}
  labels: {{- include "medical-supply-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: [{ port: {{ .Values.service.port }}, targetPort: http, protocol: TCP, name: http }]
  selector: {{- include "medical-supply-service.selectorLabels" . | nindent 4 }}
