apiVersion: v1
kind: ConfigMap
metadata:
  name: e-prescription
  namespace: helixcare
  labels: { app.kubernetes.io/name: e-prescription, helixcare.io/domain: telehealth }
data:
  LOG_LEVEL: info
  PORT: "50143"
