apiVersion: v1
kind: Service
metadata:
  name: e-prescription
  namespace: helixcare
  labels: { app.kubernetes.io/name: e-prescription, helixcare.io/domain: telehealth }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50143, targetPort: 50143 }]
  selector: { app.kubernetes.io/name: e-prescription }
