apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: { name: helixcare-aws-eu-west-1, namespace: argocd }
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/HelixCare.git
        revision: HEAD
        directories: [{ path: helm/charts/* }]
  template:
    metadata:
      name: '{{path.basename}}-aws-eu-west-1'
      labels: { cloud: aws, region: eu-west-1, gdpr: required }
    spec:
      project: helixcare
      source:
        repoURL: https://github.com/prabhat-roy/HelixCare.git
        targetRevision: HEAD
        path: '{{path}}'
        helm: { valueFiles: [values.yaml, values-aws.yaml, values-aws-eu-west-1.yaml] }
      destination: { name: helixcare-aws-eu-west-1, namespace: 'helixcare-{{path.basename}}' }
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
