apiVersion: v1
kind: ConfigMap
metadata:
  name: prescription-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: prescription-service, helixcare.io/domain: pharmacy }
data:
  LOG_LEVEL: info
  PORT: "50120"
