apiVersion: v1
kind: ConfigMap
metadata:
  name: copay-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: copay-service, helixcare.io/domain: billing }
data:
  LOG_LEVEL: info
  PORT: "50162"
