cloud: { provider: gcp, region: us-central1 }
serviceAccount: { annotations: { iam.gke.io/gcp-service-account: helixcare-medical-supply-service@PROJECT.iam.gserviceaccount.com } }
nodeSelector: { topology.kubernetes.io/region: us-central1 }
envFrom: [{ secretRef: { name: medical-supply-service-gcp-secrets } }]
