apiVersion: v1
kind: Service
metadata:
  name: encounter-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: encounter-service, helixcare.io/domain: clinical }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50080, targetPort: 50080 }]
  selector: { app.kubernetes.io/name: encounter-service }
