apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-auth-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: pre-auth-service, helixcare.io/domain: insurance }
data:
  LOG_LEVEL: info
  PORT: "50181"
