apiVersion: v1
kind: ConfigMap
metadata:
  name: po-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: po-service, helixcare.io/domain: inventory }
data:
  LOG_LEVEL: info
  PORT: "50262"
