apiVersion: v1
kind: ConfigMap
metadata:
  name: order-management
  namespace: helixcare
  labels: { app.kubernetes.io/name: order-management, helixcare.io/domain: clinical }
data:
  LOG_LEVEL: info
  PORT: "50083"
