apiVersion: v1
kind: ConfigMap
metadata:
  name: clinical-notes
  namespace: helixcare
  labels: { app.kubernetes.io/name: clinical-notes, helixcare.io/domain: clinical }
data:
  LOG_LEVEL: info
  PORT: "50081"
