apiVersion: v1
kind: Service
metadata:
  name: clinical-notes
  namespace: helixcare
  labels: { app.kubernetes.io/name: clinical-notes, helixcare.io/domain: clinical }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50081, targetPort: 50081 }]
  selector: { app.kubernetes.io/name: clinical-notes }
