cloud:
  provider: gcp
  storageClass: pd-balanced
  ingressClass: gce

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: helixcare-hipaa-audit@{{ .Values.gcp.project }}.iam.gserviceaccount.com
