apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata: { name: ci-trigger, namespace: argo-events }
spec:
  dependencies:
    - name: github-push
      eventSourceName: github
      eventName: helixcare
  triggers:
    - template:
        name: trigger-ci
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata: { generateName: helixcare-ci- }
              spec:
                entrypoint: build
                arguments: { parameters: [{ name: service, value: api-gateway }] }
                workflowTemplateRef: { name: helixcare-ci }
