apiVersion: v1
kind: Service
metadata:
  name: care-plan
  namespace: helixcare
  labels: { app.kubernetes.io/name: care-plan, helixcare.io/domain: clinical }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50082, targetPort: 50082 }]
  selector: { app.kubernetes.io/name: care-plan }
