apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: payment-service, helixcare.io/domain: billing }
data:
  LOG_LEVEL: info
  PORT: "50161"
