apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: payment-service, helixcare.io/domain: billing }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50161, targetPort: 50161 }]
  selector: { app.kubernetes.io/name: payment-service }
