apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-trail-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: audit-trail-service, helixcare.io/domain: ehr }
data:
  LOG_LEVEL: info
  PORT: "50202"
