apiVersion: v1
kind: Service
metadata:
  name: audit-trail-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: audit-trail-service, helixcare.io/domain: ehr }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50202, targetPort: 50202 }]
  selector: { app.kubernetes.io/name: audit-trail-service }
