apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clinician-bff.fullname" . }}
  labels: {{- include "clinician-bff.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: {{- include "clinician-bff.selectorLabels" . | nindent 6 }} }
  template:
    metadata:
      labels:
        {{- include "clinician-bff.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}{{- toYaml . | nindent 8 }}{{- end }}
    spec:
      serviceAccountName: {{ include "clinician-bff.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clinician-bff
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports: [{ name: http, containerPort: {{ .Values.service.targetPort }}, protocol: TCP }]
          env:
            - { name: PORT, value: "{{ .Values.service.targetPort }}" }
            {{- range $k, $v := .Values.config }}
            - { name: {{ $k }}, value: "{{ $v }}" }
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe: {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe: {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
