apiVersion: v1
kind: ConfigMap
metadata:
  name: eligibility-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: eligibility-service, helixcare.io/domain: insurance }
data:
  LOG_LEVEL: info
  PORT: "50180"
