apiVersion: v1
kind: ConfigMap
metadata:
  name: adjudication-service
  namespace: helixcare
  labels: { app.kubernetes.io/name: adjudication-service, helixcare.io/domain: insurance }
data:
  LOG_LEVEL: info
  PORT: "50183"
