apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata: { name: helixcare, namespace: flux-system }
spec:
  interval: 1m
  url: https://github.com/prabhat-roy/HelixCare.git
  ref: { branch: main }
  ignore: |
    /*
    !/helm
    !/manifests
