apiVersion: v1
kind: ConfigMap
metadata:
  name: drug-inventory
  namespace: helixcare
  labels: { app.kubernetes.io/name: drug-inventory, helixcare.io/domain: pharmacy }
data:
  LOG_LEVEL: info
  PORT: "50121"
