apiVersion: v1
kind: Service
metadata:
  name: drug-inventory
  namespace: helixcare
  labels: { app.kubernetes.io/name: drug-inventory, helixcare.io/domain: pharmacy }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50121, targetPort: 50121 }]
  selector: { app.kubernetes.io/name: drug-inventory }
