apiVersion: v1
kind: Service
metadata:
  name: clinical-nlp
  namespace: helixcare
  labels: { app.kubernetes.io/name: clinical-nlp, helixcare.io/domain: analytics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50303, targetPort: 50303 }]
  selector: { app.kubernetes.io/name: clinical-nlp }
